`timescale 1ns/1ps
`default_nettype none

// APB3 control/status register block for the DCSE accelerator prototype.
//
// Scope: this module is a bus-facing integration boundary.  It has been
// written so that an SoC wrapper can connect its job/configuration signals to
// an accelerator implementation.  It is NOT a VEGA SoC integration and it is
// NOT a protocol bridge to the AXI4-Lite interface generated by Vitis HLS.
// Those platform-dependent connections require the selected VEGA integration
// tree, address decoder, clock/reset plan, and generated HLS RTL.
//
// The slave has zero wait states: PREADY is always high.  PSLVERR is asserted
// only in the APB access phase for an unaligned, unmapped, read-only, locked,
// or otherwise invalid write.  There are no APB4-only signals such as PSTRB.
module dcse_apb3_ctrl #(
    parameter integer ADDR_WIDTH = 8,
    parameter logic [31:0] IP_ID      = 32'h4443_5345, // ASCII "DCSE"
    parameter logic [31:0] IP_VERSION = 32'h0001_0000,
    parameter integer LAYER_COUNT = 35
) (
    input  wire logic                    PCLK,
    input  wire logic                    PRESETn,
    input  wire logic                    PSEL,
    input  wire logic                    PENABLE,
    input  wire logic                    PWRITE,
    input  wire logic [ADDR_WIDTH-1:0]   PADDR,
    input  wire logic [31:0]             PWDATA,
    output logic [31:0]                  PRDATA,
    output logic                         PREADY,
    output logic                         PSLVERR,

    // Stable job configuration.  Writes are rejected while job_busy is high.
    output logic [63:0]                  cfg_input_addr,
    output logic [63:0]                  cfg_weights_addr,
    output logic [63:0]                  cfg_bias_addr,
    output logic [63:0]                  cfg_descriptor_addr,
    output logic [63:0]                  cfg_output_addr,
    output logic [5:0]                   cfg_layer_idx,

    // One PCLK pulse for an accepted CONTROL.START write.
    output logic                         job_start,
    output logic                         job_busy,
    output logic                         irq,

    // Same-clock-domain status from the accelerator wrapper.
    input  wire logic                    accel_idle,
    input  wire logic                    accel_done,
    input  wire logic                    accel_error,
    input  wire logic [7:0]              accel_error_code
);

    localparam logic [ADDR_WIDTH-1:0] REG_ID              = 'h00;
    localparam logic [ADDR_WIDTH-1:0] REG_VERSION         = 'h04;
    localparam logic [ADDR_WIDTH-1:0] REG_CONTROL         = 'h08;
    localparam logic [ADDR_WIDTH-1:0] REG_STATUS          = 'h0c;
    localparam logic [ADDR_WIDTH-1:0] REG_IRQ_ENABLE      = 'h10;
    localparam logic [ADDR_WIDTH-1:0] REG_IRQ_STATUS      = 'h14;
    localparam logic [ADDR_WIDTH-1:0] REG_LAYER_INDEX     = 'h18;
    localparam logic [ADDR_WIDTH-1:0] REG_ERROR_CODE      = 'h1c;
    localparam logic [ADDR_WIDTH-1:0] REG_INPUT_ADDR_LO   = 'h20;
    localparam logic [ADDR_WIDTH-1:0] REG_INPUT_ADDR_HI   = 'h24;
    localparam logic [ADDR_WIDTH-1:0] REG_WEIGHTS_ADDR_LO = 'h28;
    localparam logic [ADDR_WIDTH-1:0] REG_WEIGHTS_ADDR_HI = 'h2c;
    localparam logic [ADDR_WIDTH-1:0] REG_BIAS_ADDR_LO    = 'h30;
    localparam logic [ADDR_WIDTH-1:0] REG_BIAS_ADDR_HI    = 'h34;
    localparam logic [ADDR_WIDTH-1:0] REG_DESC_ADDR_LO    = 'h38;
    localparam logic [ADDR_WIDTH-1:0] REG_DESC_ADDR_HI    = 'h3c;
    localparam logic [ADDR_WIDTH-1:0] REG_OUTPUT_ADDR_LO  = 'h40;
    localparam logic [ADDR_WIDTH-1:0] REG_OUTPUT_ADDR_HI  = 'h44;
    localparam logic [ADDR_WIDTH-1:0] REG_START_COUNT     = 'h48;
    localparam logic [ADDR_WIDTH-1:0] REG_COMPLETE_COUNT  = 'h4c;

    logic [1:0]  irq_enable_q;
    logic        done_pending_q;
    logic        error_pending_q;
    logic [7:0]  error_code_q;
    logic [31:0] start_count_q;
    logic [31:0] complete_count_q;

    logic address_known;
    logic write_allowed;
    logic dynamic_write_error;

    wire logic apb_access = PSEL && PENABLE;
    wire logic apb_write  = apb_access && PWRITE;
    wire logic apb_write_commit = apb_write && PREADY && !PSLVERR;

    // always @* avoids simulator-specific always_comb sensitivity diagnostics
    // while retaining combinational behavior.
    always @* begin
        PREADY              = 1'b1;
        PRDATA              = 32'h0000_0000;
        address_known       = 1'b1;
        write_allowed       = 1'b0;
        dynamic_write_error = 1'b0;

        case (PADDR)
            REG_ID: begin
                PRDATA = IP_ID;
            end
            REG_VERSION: begin
                PRDATA = IP_VERSION;
            end
            REG_CONTROL: begin
                PRDATA        = 32'h0000_0000;
                write_allowed = 1'b1;
                // Only bit 0 is defined.  START is rejected if a job is
                // active or the downstream accelerator is not idle.
                dynamic_write_error =
                    (|PWDATA[31:1]) ||
                    (PWDATA[0] && (job_busy || !accel_idle));
            end
            REG_STATUS: begin
                PRDATA[0] = job_busy;
                PRDATA[1] = done_pending_q;
                PRDATA[2] = error_pending_q;
                PRDATA[3] = accel_idle;
                PRDATA[4] = irq;
            end
            REG_IRQ_ENABLE: begin
                PRDATA[1:0]  = irq_enable_q;
                write_allowed = 1'b1;
                dynamic_write_error = |PWDATA[31:2];
            end
            REG_IRQ_STATUS: begin
                PRDATA[0]   = done_pending_q;
                PRDATA[1]   = error_pending_q;
                write_allowed = 1'b1;
                // W1C registers intentionally ignore unused write bits.
            end
            REG_LAYER_INDEX: begin
                PRDATA[5:0]  = cfg_layer_idx;
                write_allowed = 1'b1;
                dynamic_write_error =
                    job_busy ||
                    (|PWDATA[31:6]) ||
                    (PWDATA[5:0] >= LAYER_COUNT);
            end
            REG_ERROR_CODE: begin
                PRDATA[7:0] = error_code_q;
            end
            REG_INPUT_ADDR_LO: begin
                PRDATA        = cfg_input_addr[31:0];
                write_allowed = 1'b1;
                dynamic_write_error = job_busy;
            end
            REG_INPUT_ADDR_HI: begin
                PRDATA        = cfg_input_addr[63:32];
                write_allowed = 1'b1;
                dynamic_write_error = job_busy;
            end
            REG_WEIGHTS_ADDR_LO: begin
                PRDATA        = cfg_weights_addr[31:0];
                write_allowed = 1'b1;
                dynamic_write_error = job_busy;
            end
            REG_WEIGHTS_ADDR_HI: begin
                PRDATA        = cfg_weights_addr[63:32];
                write_allowed = 1'b1;
                dynamic_write_error = job_busy;
            end
            REG_BIAS_ADDR_LO: begin
                PRDATA        = cfg_bias_addr[31:0];
                write_allowed = 1'b1;
                dynamic_write_error = job_busy;
            end
            REG_BIAS_ADDR_HI: begin
                PRDATA        = cfg_bias_addr[63:32];
                write_allowed = 1'b1;
                dynamic_write_error = job_busy;
            end
            REG_DESC_ADDR_LO: begin
                PRDATA        = cfg_descriptor_addr[31:0];
                write_allowed = 1'b1;
                dynamic_write_error = job_busy;
            end
            REG_DESC_ADDR_HI: begin
                PRDATA        = cfg_descriptor_addr[63:32];
                write_allowed = 1'b1;
                dynamic_write_error = job_busy;
            end
            REG_OUTPUT_ADDR_LO: begin
                PRDATA        = cfg_output_addr[31:0];
                write_allowed = 1'b1;
                dynamic_write_error = job_busy;
            end
            REG_OUTPUT_ADDR_HI: begin
                PRDATA        = cfg_output_addr[63:32];
                write_allowed = 1'b1;
                dynamic_write_error = job_busy;
            end
            REG_START_COUNT: begin
                PRDATA = start_count_q;
            end
            REG_COMPLETE_COUNT: begin
                PRDATA = complete_count_q;
            end
            default: begin
                address_known = 1'b0;
                PRDATA        = 32'h0000_0000;
            end
        endcase

        // APB3 defines PSLVERR only for the final access cycle.  This slave
        // completes every transfer immediately, so PENABLE qualifies PSLVERR.
        PSLVERR = apb_access &&
                  ((|PADDR[1:0]) ||
                   !address_known ||
                   (PWRITE && (!write_allowed || dynamic_write_error)));
    end

    assign irq = (done_pending_q  && irq_enable_q[0]) ||
                 (error_pending_q && irq_enable_q[1]);

    always_ff @(posedge PCLK or negedge PRESETn) begin
        if (!PRESETn) begin
            cfg_input_addr      <= 64'h0;
            cfg_weights_addr    <= 64'h0;
            cfg_bias_addr       <= 64'h0;
            cfg_descriptor_addr <= 64'h0;
            cfg_output_addr     <= 64'h0;
            cfg_layer_idx       <= 6'h0;
            job_start           <= 1'b0;
            job_busy            <= 1'b0;
            irq_enable_q        <= 2'b00;
            done_pending_q      <= 1'b0;
            error_pending_q     <= 1'b0;
            error_code_q        <= 8'h00;
            start_count_q       <= 32'h0;
            complete_count_q    <= 32'h0;
        end else begin
            job_start <= 1'b0;

            if (apb_write_commit) begin
                case (PADDR)
                    REG_CONTROL: begin
                        if (PWDATA[0]) begin
                            job_start        <= 1'b1;
                            job_busy         <= 1'b1;
                            done_pending_q   <= 1'b0;
                            error_pending_q  <= 1'b0;
                            error_code_q     <= 8'h00;
                            start_count_q    <= start_count_q + 1'b1;
                        end
                    end
                    REG_IRQ_ENABLE: begin
                        irq_enable_q <= PWDATA[1:0];
                    end
                    REG_IRQ_STATUS: begin
                        if (PWDATA[0])
                            done_pending_q <= 1'b0;
                        if (PWDATA[1]) begin
                            error_pending_q <= 1'b0;
                            error_code_q    <= 8'h00;
                        end
                    end
                    REG_LAYER_INDEX: begin
                        cfg_layer_idx <= PWDATA[5:0];
                    end
                    REG_INPUT_ADDR_LO: begin
                        cfg_input_addr[31:0] <= PWDATA;
                    end
                    REG_INPUT_ADDR_HI: begin
                        cfg_input_addr[63:32] <= PWDATA;
                    end
                    REG_WEIGHTS_ADDR_LO: begin
                        cfg_weights_addr[31:0] <= PWDATA;
                    end
                    REG_WEIGHTS_ADDR_HI: begin
                        cfg_weights_addr[63:32] <= PWDATA;
                    end
                    REG_BIAS_ADDR_LO: begin
                        cfg_bias_addr[31:0] <= PWDATA;
                    end
                    REG_BIAS_ADDR_HI: begin
                        cfg_bias_addr[63:32] <= PWDATA;
                    end
                    REG_DESC_ADDR_LO: begin
                        cfg_descriptor_addr[31:0] <= PWDATA;
                    end
                    REG_DESC_ADDR_HI: begin
                        cfg_descriptor_addr[63:32] <= PWDATA;
                    end
                    REG_OUTPUT_ADDR_LO: begin
                        cfg_output_addr[31:0] <= PWDATA;
                    end
                    REG_OUTPUT_ADDR_HI: begin
                        cfg_output_addr[63:32] <= PWDATA;
                    end
                    default: begin
                        // All other writes are rejected before commit.
                    end
                endcase
            end

            // Completion events have priority over a simultaneous W1C access,
            // so software cannot lose a newly arrived interrupt cause.
            if (job_busy && accel_error) begin
                job_busy         <= 1'b0;
                error_pending_q  <= 1'b1;
                error_code_q     <= accel_error_code;
                complete_count_q <= complete_count_q + 1'b1;
            end else if (job_busy && accel_done) begin
                job_busy         <= 1'b0;
                done_pending_q   <= 1'b1;
                complete_count_q <= complete_count_q + 1'b1;
            end
        end
    end

    initial begin : validate_parameters
        if (ADDR_WIDTH < 8)
            $error("ADDR_WIDTH must be at least 8");
        if (LAYER_COUNT < 1 || LAYER_COUNT > 64)
            $error("LAYER_COUNT must be between 1 and 64");
    end

endmodule

`default_nettype wire
